/*
 * Copyright (c) 2026 Right&Above, LLC
 * https://rightandabove.com
 * SPDX-License-Identifier: MIT
 */

import { randomUUID } from 'node:crypto';
import type {
  Credentials,
  FolderInfo,
  ScanOptions,
  ScanProgress,
} from '../../shared/domain.js';
import type { Db } from '../db/connection.js';
import { upsertAccount } from '../db/accounts.repo.js';
import { upsertFolder } from '../db/folders.repo.js';
import { loadAllBodiesDecrypted } from '../db/message-bodies.repo.js';
import type { AddressRow } from '../db/addresses.repo.js';
import type { FolderState, ImapClientLike } from '../imap/client.js';
import { electronSafeStorageCipher, type CredentialCipher } from '../security/safe-storage.js';
import { CancelledError } from '../imap/errors.js';
import { withReconnectRetry } from '../imap/retry.js';
import { normalizeEmail } from '../../shared/email-normalize.js';
import {
  DEFAULT_HEURISTICS_CONFIG,
  heuristicsConfigFromScanOptions,
  type HeuristicsConfig,
} from '../../shared/heuristics-config.js';
import { createThrottledProgress } from './progress.js';
import {
  deriveMyAddressesFromSent,
  ingestFolder,
  isSentFolder,
} from './ingestion.js';
import { deepScanBodies } from './body-scan.js';
import {
  classifyAndPersistAddresses,
  rebuildAddressesAggregate,
} from './aggregation.js';
import {
  NOOP_METRICS,
  aggregateDurationsByName,
  type MetricsCollector,
} from './metrics.js';
import {
  formatRate,
  makeNoopLogger,
  tracePhase,
  type PipelineLogger,
} from './logger.js';
import { type Parser } from './parser-pool.js';
import type { ImapConnectionPool } from '../imap/connection-pool.js';

export interface ScanInput {
  // UUID generated by the IPC layer; carried through the entire run so
  // every log line — pipeline, IMAP retries, body-scan, aggregation —
  // is grep-able to one specific scan attempt. Optional in callers
  // (tests omit it); `runScan` falls back to a fresh UUID if absent
  // so the log prefix is always populated.
  readonly runId?: string;
  readonly credentials: Credentials;
  readonly options: ScanOptions;
  readonly onProgress: (event: ScanProgress) => void;
  // Optional. When supplied, the runner re-aggregates and re-classifies
  // after each folder ingest and emits the *delta* of contacts that just
  // became "kept" since the previous snapshot. Kept-membership is monotonic
  // in our heuristics, so the renderer can append rows append-only without
  // re-sorting or removing previously-emitted ones.
  readonly onSnapshot?: (delta: readonly AddressRow[]) => void;
  readonly signal: AbortSignal;
}

export interface ScanResult {
  readonly accountId: number;
  readonly contactsCount: number;
}

export interface ScanRunnerDeps {
  readonly db: Db;
  readonly client: ImapClientLike;
  readonly heuristics?: HeuristicsConfig;
  readonly progressIntervalMs?: number;
  // Override Date.now for deterministic tests.
  readonly now?: () => number;
  // Backoff delays (ms) between reconnect retries on transient IMAP failures.
  // Length determines the retry budget — N entries means N retries / N+1 total
  // attempts. Production default is 1s, 2s, 4s; tests typically pass [0, 0, 0]
  // to exercise the retry path without sleeping.
  readonly imapRetryBackoffMs?: readonly number[];
  // Cipher used for encrypting/decrypting cached message bodies. Tests can
  // inject an in-memory stub; production code defaults to the Electron
  // safeStorage cipher used elsewhere.
  readonly bodyCipher?: CredentialCipher;
  // Structured logger. IPC handler wires an electron-log-backed instance;
  // bench harness uses console; unit tests fall through to noop. Every
  // phase emits `[scan run=<id>] [phase] start/end name=<X> …` lines so
  // a grep on main.log gives the full timeline of a run.
  readonly log?: PipelineLogger;
  // Per-run metrics collector. When non-noop, the bench harness flushes
  // its snapshot to JSONL after the scan completes. NOOP_METRICS by
  // default keeps the in-app path free of bookkeeping cost.
  readonly metrics?: MetricsCollector;
  // mailparser strategy. IPC handler hands in a `worker-pool` parser
  // for production scans so HTML parsing runs in parallel on background
  // threads. Unit tests / fallback omit this; body-scan defaults to
  // `createInlineParser()` internally (behaviour-identical to the
  // pre-pool path).
  readonly parser?: Parser;
  // IMAP connection pool. When supplied, the runner fans out per-folder
  // ingest (and per-folder deep-scan) across multiple parallel TCP
  // sessions instead of serialising on `deps.client`. Production wiring
  // creates the pool in the IPC scan handler and closes it in
  // `finally`. Unit tests omit this; the runner falls back to serial
  // ingest on `deps.client`, which keeps the per-folder streaming-
  // snapshot path byte-identical to the pre-pool flow.
  readonly pool?: ImapConnectionPool;
}

// Orchestrates one scan end-to-end. The pipeline:
//   1. Connect IMAP, persist account row.
//   2. List folders, apply include/exclude/includeShareable.
//   3. Identify Sent folders, fetch their headers, derive myAddresses.
//   4. For each folder: ingest new headers in batches inside one
//      transaction per folder. Cancellation rolls the folder back.
//   5. Optional Pass 2 (parseBodies on): re-aggregate, classify, deep-fetch
//      bodies for kept candidates, store encrypted, re-classify with
//      bodyMatcher.
//   6. Final aggregate + classify, persist tags.
//   7. Disconnect.
export async function runScan(
  input: ScanInput,
  deps: ScanRunnerDeps,
): Promise<ScanResult> {
  const { credentials, options, onProgress, onSnapshot, signal } = input;
  const { db, client } = deps;
  const runId = input.runId ?? randomUUID();
  const logger = deps.log ?? makeNoopLogger(runId);
  const metrics = deps.metrics ?? NOOP_METRICS;
  // Per-scan heuristics: merge the user's directionMode + minMessages into
  // the bidirectionality threshold; everything else (automation/role
  // regexes) keeps the default. The deps override only kicks in for tests
  // that want a fully custom config.
  const baseConfig = deps.heuristics ?? DEFAULT_HEURISTICS_CONFIG;
  const config: HeuristicsConfig = heuristicsConfigFromScanOptions(options, baseConfig);
  const now = deps.now ?? Date.now;
  const progress = createThrottledProgress(onProgress, deps.progressIntervalMs ?? 100);
  const backoffMs = deps.imapRetryBackoffMs;
  const bodyCipher = deps.bodyCipher ?? electronSafeStorageCipher;

  function checkAbort(): void {
    if (signal.aborted) throw new CancelledError('scan cancelled');
  }

  // Top-level span wraps the whole run so the summary line at the end
  // can read total wall time without measuring twice. Failure path
  // closes the span via the catch arm so an exception doesn't leave an
  // open span in the metrics snapshot.
  const endRunSpan = metrics.startSpan('runScan', {
    runId,
    parseBodies: options.parseBodies,
    directionMode: options.directionMode,
    minMessages: options.minMessages,
  });
  logger.info('run-start', {
    parseBodies: options.parseBodies,
    directionMode: options.directionMode,
    minMessages: options.minMessages,
    folderInclude: options.folderInclude?.length ?? 0,
    folderExclude: options.folderExclude?.length ?? 0,
  });

  progress.emit({ phase: 'connecting', processed: 0, total: 0 });
  // If the caller (e.g. the IPC layer) already opened a session, reuse it
  // and leave teardown to them. Otherwise own the lifecycle ourselves.
  const ownsConnection = !client.isConnected();
  if (ownsConnection) {
    const endConnect = tracePhase(logger, metrics, 'imap.connect', {
      host: credentials.host,
      port: credentials.port,
    });
    try {
      await client.connect(credentials, signal);
    } finally {
      endConnect();
    }
  }

  try {
    const loginNorm = normalizeEmail(credentials.username);
    let account = upsertAccount(db, {
      host: credentials.host,
      username: credentials.username,
      myAddresses: [loginNorm],
    });

    progress.emit({ phase: 'enumerating', processed: 0, total: 0 });
    const endList = tracePhase(logger, metrics, 'imap.listFolders');
    const allFolders = await withReconnectRetry(
      { client, credentials, signal, opName: 'listFolders', ...(backoffMs ? { backoffMs } : {}) },
      () => client.listFolders(signal),
    );
    endList({ folderCount: allFolders.length });
    logger.info('folders-received', {
      total: allFolders.length,
      sample: allFolders.slice(0, 5).map((f) => f.path).join(','),
    });
    const folders = applyFolderFilters(allFolders, options);
    const sentFolders = folders.filter(isSentFolder);
    logger.info('folders-filtered', {
      selected: folders.length,
      sent: sentFolders.length,
      sentPaths: sentFolders.map((f) => f.path).join(','),
    });

    const endDerive = tracePhase(logger, metrics, 'derive-myAddresses', {
      sentFolders: sentFolders.length,
    });
    const myAddresses = await withReconnectRetry(
      {
        client,
        credentials,
        signal,
        opName: 'deriveMyAddressesFromSent',
        ...(backoffMs ? { backoffMs } : {}),
      },
      () => deriveMyAddressesFromSent(runId, client, sentFolders, credentials, signal, logger, metrics),
    );
    endDerive({ addresses: myAddresses.size });
    account = upsertAccount(db, {
      host: credentials.host,
      username: credentials.username,
      myAddresses: [...myAddresses],
    });

    const folderStates = new Map<string, FolderState>();
    // Reserve a folder_id for every folder included in this scan up front,
    // so the aggregate filter knows the scope BEFORE we ingest anything.
    // Without this, a scan over a single empty folder would still surface
    // contacts pulled from prior scans of OTHER folders cached in the DB.
    const selectedFolderIds = new Set<number>();
    const endStates = tracePhase(logger, metrics, 'imap.getFolderStates', {
      folders: folders.length,
    });
    for (const folder of folders) {
      checkAbort();
      const state = await withReconnectRetry(
        {
          client,
          credentials,
          signal,
          opName: `getFolderState '${folder.path}'`,
          ...(backoffMs ? { backoffMs } : {}),
        },
        () => client.getFolderState(folder.path, signal),
      );
      folderStates.set(folder.path, state);
      const row = upsertFolder(db, {
        accountId: account.id,
        path: folder.path,
        uidvalidity: state.uidvalidity,
      });
      selectedFolderIds.add(row.id);
    }
    let totalEstimate = 0;
    for (const s of folderStates.values()) totalEstimate += s.exists;
    endStates({ totalMessages: totalEstimate });

    // Shared ingest counter — all parallel ingestFolder calls bump it,
    // progress shows the running total across folders. Pre-pool the
    // counter was a plain `let` passed by value; now it's a ref-object
    // so the runner doesn't have to thread a sequential return through
    // a Promise.all.
    const ingestCounter = { processed: 0, totalEstimate };
    let priorKept = new Set<string>();
    let lastKept = new Set<string>();

    // Parallel ingest is safe only when we don't need a per-folder
    // streaming snapshot — Pass 2 (parseBodies) always suppresses
    // snapshots, and callers without `onSnapshot` don't watch them
    // anyway. The streaming path keeps the sequential shape so the
    // delta-vs-priorKept logic stays correct.
    const parallelIngest =
      deps.pool !== undefined && (options.parseBodies || onSnapshot === undefined);
    const dbPool = deps.pool;

    async function ingestOne(folder: FolderInfo, c: ImapClientLike): Promise<void> {
      checkAbort();
      const state = folderStates.get(folder.path);
      if (!state) return;
      await ingestFolder({
        runId,
        db,
        client: c,
        credentials,
        folder,
        state,
        accountId: account.id,
        myAddresses,
        signal,
        counter: ingestCounter,
        progress,
        now,
        logger,
        metrics,
        ...(backoffMs ? { backoffMs } : {}),
      });
    }

    if (parallelIngest && dbPool) {
      logger.info('ingest-parallel', { folders: folders.length, poolSize: dbPool.size });
      await Promise.all(
        folders.map((folder) =>
          dbPool.withConnection(`ingest '${folder.path}'`, (c) => ingestOne(folder, c)),
        ),
      );
    } else {
      logger.info('ingest-sequential', { folders: folders.length });
      for (const folder of folders) {
        if (dbPool) {
          await dbPool.withConnection(`ingest '${folder.path}'`, (c) =>
            ingestOne(folder, c),
          );
        } else {
          await ingestOne(folder, client);
        }

        // Per-folder snapshot: only when the caller asked for streaming AND
        // the user did NOT opt into deep scan. Deep scan can SHRINK the kept
        // set after Pass 2 (inline-unsubscribe / body word filter), and the
        // streaming UI is append-only — so we suppress per-folder snapshots
        // and emit a single final delta after Pass 2 is done.
        if (onSnapshot && !options.parseBodies) {
          checkAbort();
          const endSnapAgg = tracePhase(logger, metrics, 'snapshot.aggregate', {
            afterFolder: folder.path,
          });
          rebuildAddressesAggregate(
            db,
            account.id,
            myAddresses,
            selectedFolderIds,
            options,
            undefined,
            logger,
            metrics,
          );
          endSnapAgg();
          const endSnapClassify = tracePhase(logger, metrics, 'snapshot.classify', {
            afterFolder: folder.path,
          });
          const { keptEmails, rowsByEmail } = classifyAndPersistAddresses(
            db,
            account.id,
            selectedFolderIds,
            config,
            checkAbort,
            logger,
            metrics,
          );
          endSnapClassify({ kept: keptEmails.size });
          const newlyKept = [...keptEmails].filter((e) => !priorKept.has(e));
          if (newlyKept.length > 0) {
            const deltaRows = newlyKept
              .map((e) => rowsByEmail.get(e))
              .filter((r): r is AddressRow => r !== undefined);
            onSnapshot(deltaRows);
          }
          priorKept = keptEmails;
          lastKept = keptEmails;
        }
      }
    }
    // After parallel-ingest, `processed` is whatever the counter holds.
    // After sequential streaming-snapshot ingest, same — the counter is
    // monotonic across both paths.
    const processed = ingestCounter.processed;

    // Pass 2 — fetch bodies for kept-candidates from the header-only pass,
    // encrypt + store, and flip `has_inline_unsubscribe` so the final
    // classify can see it. Skipped when the user did not opt in or when
    // safeStorage is unavailable on this machine.
    let bodyMatcher: ((messageId: number) => string | null) | undefined;
    if (options.parseBodies) {
      if (!bodyCipher.isAvailable()) {
        logger.warn('deep-scan-skipped', {
          reason: 'bodyCipher unavailable — falling back to header-only filters',
        });
      } else {
        // Provisional aggregate + classify on headers alone to identify
        // which contacts are worth fetching bodies for. Both passes are
        // CPU-bound and silent (no IO) — emit phase events around them so
        // the UI shows "aggregating / classifying" instead of freezing on
        // the prior "fetching X/X" stamp for 5–15s on a 20k mailbox.
        progress.emit({
          phase: 'aggregating',
          currentFolder: 'pre-pass',
          processed,
          total: totalEstimate,
        });
        progress.flush();
        const endPreAgg = tracePhase(logger, metrics, 'prepass.aggregate');
        rebuildAddressesAggregate(
          db,
          account.id,
          myAddresses,
          selectedFolderIds,
          options,
          undefined,
          logger,
          metrics,
        );
        endPreAgg();
        progress.emit({
          phase: 'classifying',
          currentFolder: 'pre-pass',
          processed,
          total: totalEstimate,
        });
        progress.flush();
        const endPreClassify = tracePhase(logger, metrics, 'prepass.classify');
        const provisional = classifyAndPersistAddresses(
          db,
          account.id,
          selectedFolderIds,
          config,
          checkAbort,
          logger,
          metrics,
        );
        endPreClassify({ kept: provisional.keptEmails.size });
        if (provisional.keptEmails.size > 0) {
          progress.emit({
            phase: 'fetching-bodies',
            currentFolder: `${provisional.keptEmails.size} contacts`,
            processed: 0,
            total: 0,
          });
          progress.flush();
          const endDeep = tracePhase(logger, metrics, 'deepScanBodies', {
            keptCandidates: provisional.keptEmails.size,
          });
          await deepScanBodies({
            runId,
            db,
            client,
            credentials,
            accountId: account.id,
            keptEmails: provisional.keptEmails,
            folderIds: selectedFolderIds,
            signal,
            cipher: bodyCipher,
            inlineUnsubscribeRegex: config.inlineUnsubscribeRegex,
            now,
            progress,
            logger,
            metrics,
            ...(deps.parser ? { parser: deps.parser } : {}),
            ...(deps.pool ? { pool: deps.pool } : {}),
            ...(backoffMs ? { backoffMs } : {}),
          });
          endDeep();
        }
        // Pre-load every decrypted body for this account into a Map
        // once, instead of the per-message `getMessageBodyDecrypted`
        // SQL the final-pass aggregator used to do (N+1 over 100k
        // messages = ~2 s of pure SQLite overhead). One SQL JOIN,
        // one decrypt loop, then O(1) Map.get during aggregation.
        const endBodyLoad = tracePhase(logger, metrics, 'final.bodyMatcher.load', {
          parser: deps.parser?.kind ?? 'inline',
        });
        const bodyMap = loadAllBodiesDecrypted(db, account.id, bodyCipher);
        endBodyLoad({ bodies: bodyMap.size });
        bodyMatcher = (messageId: number): string | null =>
          bodyMap.get(messageId) ?? null;
      }
    }

    // Final canonical aggregate + classify. With deep scan enabled, this
    // pass also feeds decrypted bodies into the include/exclude word
    // matchers via `bodyMatcher`. Without deep scan, the call is identical
    // to the previous version of this block.
    {
      progress.emit({ phase: 'aggregating', processed, total: totalEstimate });
      progress.flush();
      const endFinalAgg = tracePhase(logger, metrics, 'final.aggregate', {
        withBodyMatcher: bodyMatcher !== undefined,
      });
      rebuildAddressesAggregate(
        db,
        account.id,
        myAddresses,
        selectedFolderIds,
        options,
        bodyMatcher,
        logger,
        metrics,
      );
      endFinalAgg();

      progress.emit({ phase: 'classifying', processed, total: totalEstimate });
      progress.flush();
      const endFinalClassify = tracePhase(logger, metrics, 'final.classify');
      const { keptEmails, rowsByEmail } = classifyAndPersistAddresses(
        db,
        account.id,
        selectedFolderIds,
        config,
        checkAbort,
        logger,
        metrics,
      );
      endFinalClassify({ kept: keptEmails.size });
      lastKept = keptEmails;

      // When streaming AND we suppressed per-folder snapshots above
      // (deep-scan path), emit a single final delta so the UI ends up in
      // sync with the post-Pass-2 kept set.
      if (onSnapshot && options.parseBodies) {
        const deltaRows = [...keptEmails]
          .map((e) => rowsByEmail.get(e))
          .filter((r): r is AddressRow => r !== undefined);
        if (deltaRows.length > 0) onSnapshot(deltaRows);
      }
    }

    progress.emit({ phase: 'done', processed, total: totalEstimate });
    progress.flush();

    endRunSpan({ contacts: lastKept.size, processed });

    // Summary one-liner: every named phase's total wall time, derived
    // from the metrics snapshot. Grep on `[scan run=<id>] summary` after
    // a long scan gives the entire timing breakdown in one log entry.
    const totalsByName = aggregateDurationsByName(metrics.snapshot());
    const summaryFields: Record<string, unknown> = {
      total_ms: totalsByName.get('runScan')?.totalMs?.toFixed(0) ?? '0',
      processed,
      contacts: lastKept.size,
      rate: formatRate(processed, totalsByName.get('runScan')?.totalMs ?? 0, 'msgs'),
    };
    for (const [name, agg] of totalsByName) {
      if (name === 'runScan') continue;
      summaryFields[`${name}_ms`] = agg.totalMs.toFixed(0);
      if (agg.count > 1) summaryFields[`${name}_n`] = agg.count;
    }
    logger.info('summary', summaryFields);

    return { accountId: account.id, contactsCount: lastKept.size };
  } catch (err) {
    endRunSpan({ error: err instanceof Error ? err.message : String(err) });
    logger.error('run-error', {
      reason: err instanceof Error ? err.message : String(err),
    });
    throw err;
  } finally {
    if (ownsConnection) {
      await client.disconnect();
    }
  }
}

// Apply the user's folder-include / folder-exclude lists from ScanOptions.
// Empty include = "all"; exclude wins over include when both list a folder.
function applyFolderFilters(
  folders: readonly FolderInfo[],
  options: ScanOptions,
): FolderInfo[] {
  const includeSet = options.folderInclude ? new Set(options.folderInclude) : null;
  const excludeSet = options.folderExclude ? new Set(options.folderExclude) : null;
  return folders.filter((f) => {
    if (includeSet && !includeSet.has(f.path)) return false;
    if (excludeSet && excludeSet.has(f.path)) return false;
    return true;
  });
}
